### ISSUE TITLE
NullPointerException with Proguard

### ISSUE THREAD

**Issue by DarkAbhi** [muthukrishnan-suresh/soul-surfer-android#5]
`10-14 23:45:14.224 E/AndroidRuntime( 9805): java.lang.NullPointerException: throw with null exception
10-14 23:45:14.224 E/AndroidRuntime( 9805): 	at d.h.a.d.c.d.run(SoulSurferRepository.java:13)
10-14 23:45:14.224 E/AndroidRuntime( 9805): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-14 23:45:14.224 E/AndroidRuntime( 9805): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-14 23:45:14.224 E/AndroidRuntime( 9805): 	at java.lang.Thread.run(Thread.java:764)`

Proguard rules

`#Jsoup
-keep public class org.jsoup.** {
public *;
}`

`-keeppackagenames org.jsoup.nodes`

**Comment by muthukrishnan-suresh** [comment]
@DarkAbhi Will fix and make a release in few hours.

**Comment by DarkAbhi** [comment]
> 
> 
> @DarkAbhi Will fix and make a release in few hours.

Alright thanks for addressing!

**Comment by muthukrishnan-suresh** [comment]
@DarkAbhi fixed proguard related issues as part of version [1.1.0](https://github.com/muthukrishnan-suresh/soul-surfer-android/releases/tag/1.1.0)
